version: "3"

services:
  db:
    image: postgres
    container_name: postgres_zmall_tim
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=zmall_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - redis
  web:
    build: .
    ports:
      - 8011:8000
    container_name: zmall_restapi
    environment:
      - POSTGRES_NAME=zmall_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media_volume:/zmall_rest/mediafiles
      - static_volume:/zmall_rest/staticfiles
    restart: unless-stopped
    depends_on:
      - db
      - redis
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/zmall_rest/staticfiles
    depends_on:
      - celery
    ports:
      - 8011:80
  redis:
    image: redis:alpine
  celery:
    restart: unless-stopped
    build:
      context: .
    command: celery -A config worker -l info
    env_file:
      - ./.env
    depends_on:
      - web


volumes:
    postgres_data:
    static_volume:
    media_volume:
