# Generated by Django 4.0.7 on 2022-09-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_alter_post_status_alter_postcomplaint_choice_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_payment', to='adds.post'),
            preserve_default=False,
        ),
    ]
