# Generated by Django 4.0.7 on 2022-09-27 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_alter_post_status_alter_postcomplaint_choice_and_more'),
        ('payment', '0002_payment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_payment', to='adds.post'),
        ),
    ]
