# Generated by Django 4.0.7 on 2022-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_storetarsaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetarsaction',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
