# Generated by Django 4.0.7 on 2022-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
