# Generated by Django 4.1 on 2022-09-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="city",
            name="title",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="adds.city",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="from_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_activated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="subscription",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="adds.subscription"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="post",
            name="to_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="wa_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="title",
            field=models.CharField(
                max_length=1000, unique=True, verbose_name="Subcategory"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
