# Generated by Django 4.0.7 on 2022-09-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomplaint',
            name='choice',
            field=models.CharField(blank=True, choices=[('Неверная рубрика', 'Неверная рубрика'), ('Запрещенный товар', 'Запрещенный товар/услуги'), ('Объявление не актуально', 'Объявление не актуально'), ('Неверный адрес', 'Неверный адрес'), ('Другое', 'Другое'), ('', '')], default='', max_length=100, null=True),
        ),
    ]
