# Generated by Django 4.0.7 on 2022-09-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('в рассмотрени', 'в рассмотрении'), ('одобрено', 'одобрено'), ('отклонено', 'отклонено')], default='in_progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Добавить стикер "Срочно"', 'Добавить стикер "Срочно"'), ('Выделить цветом', 'Выделить цветом')], max_length=100),
        ),
    ]
