# Generated by Django 4.0.7 on 2022-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('urgent', 'Добавить стикер "Срочно"'), ('highlight', 'Выделить цветом')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('5 days', '5'), ('10 days', '10'), ('15 days', '15'), ('20 days', '20'), ('25 days', '25'), ('30 days', '30')], max_length=100),
        ),
    ]
