# Generated by Django 4.0.7 on 2022-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('5 days', '5 days'), ('10 days', '10 days'), ('15 days', '15 days'), ('20 days', '20 days'), ('25 days', '25 days'), ('30 days', '30 days')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
