# Generated by Django 4.1 on 2022-08-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='phonepost',
            name='phone_number_0',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='image',
        ),
        migrations.AddField(
            model_name='phonepost',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimages',
            name='images',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('verified', 'verified'), ('rejected', 'rejected')], default=('in_progress', 'in_progress'), max_length=100),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='adds.post'),
        ),
    ]
