# Generated by Django 4.0.7 on 2022-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_alter_post_status_alter_postcomplaint_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
