# Generated by Django 4.0.7 on 2022-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_alter_post_status_alter_subscription_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomplaint',
            name='choice',
            field=models.CharField(blank=True, choices=[('Неверная рубрика', 'Неверная рубрика'), ('Запрещенный товар', 'Запрещенный товар'), ('Объявление не актуально', 'Объявление не актуально'), ('Неверный адрес', 'Неверный адрес'), ('Другое', 'Другое'), ('', '')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], max_length=100),
        ),
    ]
