# Generated by Django 4.0.7 on 2022-09-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_alter_favorite_post_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
