# Generated by Django 4.0.7 on 2022-09-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_remove_subscription_end_date_subscription_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_created',
        ),
    ]
