# Generated by Django 4.1 on 2022-09-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0002_alter_category_icon_image_alter_city_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Subcategory"
            ),
        ),
    ]
