# Generated by Django 4.1 on 2022-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0003_alter_post_description_alter_post_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=10000),
        ),
    ]
