# Generated by Django 4.0.7 on 2022-09-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0003_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subscription',
        ),
        migrations.AddField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='adds.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('urgent', 'urgent'), ('highlight', 'highlight')], max_length=100),
        ),
    ]
