# Generated by Django 4.0.7 on 2022-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0003_alter_postcomplaint_choice_alter_subscription_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Добавить стикер "Срочно"', 'Добавить стикер "Срочно"'), ('Выделить цветом', 'Выделить цветом'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('', '')], default='', max_length=100),
        ),
    ]
