# Generated by Django 4.1 on 2022-09-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_alter_subscription_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(default=('ordinary', 'ordinary'), on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='adds.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('highlight', 'highlight'), ('urgent', 'urgent')], max_length=100),
        ),
    ]
