# Generated by Django 4.0.7 on 2022-09-20 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adds', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='post',
        ),
        migrations.AddField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='adds.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
