# Generated by Django 4.0.7 on 2022-09-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_remove_favorite_post_favorite_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=500000000, max_length=10)),
                ('view', models.IntegerField(default=0)),
                ('post_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_post', to='adds.post')),
            ],
        ),
        migrations.AddField(
            model_name='views',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='views',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='views',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Views_Post', to='adds.post'),
        ),
        migrations.AlterField(
            model_name='views',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ViewsContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='adds.phonenumber')),
                ('view_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_contact', to='adds.views')),
            ],
        ),
    ]
