# Generated by Django 4.0.7 on 2022-09-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_alter_subscription_choice_alter_subscription_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontacts',
            name='post_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_phone', to='adds.post'),
        ),
    ]
