# Generated by Django 4.1 on 2022-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0004_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
