# Generated by Django 4.0.7 on 2022-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_remove_post_subscription_post_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('urgent', 'urgent'), ('highlight', 'highlight')], max_length=100),
        ),
    ]
