# Generated by Django 4.1 on 2022-09-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0005_alter_post_subscription_alter_subscription_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='adds.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('highlight', 'highlight'), ('urgent', 'urgent'), ('ordinary', 'ordinary')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
