# Generated by Django 4.0.7 on 2022-09-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0005_alter_postcontacts_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontacts',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
