# Generated by Django 4.1 on 2022-09-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0006_alter_post_subscription_alter_subscription_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-id']},
        ),
    ]
