# Generated by Django 4.1 on 2022-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0006_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
