# Generated by Django 4.0.7 on 2022-09-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0006_alter_subscription_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='adds.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('urgent', 'urgent'), ('highlight', 'highlight')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
