# Generated by Django 4.0.7 on 2022-09-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0007_alter_post_subscription_alter_subscription_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
