# Generated by Django 4.1 on 2022-09-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0007_alter_subscription_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontacts',
            old_name='phone_number',
            new_name='add_number',
        ),
    ]
