# Generated by Django 4.1 on 2022-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0008_rename_phone_number_postcontacts_add_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_category',
            field=models.IntegerField(default=0),
        ),
    ]
