# Generated by Django 4.0.7 on 2022-09-14 09:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0008_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='adds.city'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(default='No email', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_price',
            field=models.DecimalField(decimal_places=2, default='Договорная', max_digits=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='No number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='wa_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='No number', max_length=128, region=None),
        ),
    ]
