# Generated by Django 4.1 on 2022-09-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0009_category_count_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count_category',
        ),
    ]
