# Generated by Django 4.0.7 on 2022-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0009_alter_post_city_alter_post_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='from_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
