# Generated by Django 4.1 on 2022-09-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0010_remove_category_count_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='highlight',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='adds.category'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('urgent', 'urgent'), ('ordinary', 'ordinary')], max_length=100),
        ),
    ]
