# Generated by Django 4.0.7 on 2022-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0010_alter_post_from_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
