# Generated by Django 4.0.7 on 2022-09-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0011_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='icon_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
