# Generated by Django 4.1 on 2022-09-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0011_subscription_highlight_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='highlight',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('highlight', 'highlight'), ('urgent', 'urgent'), ('ordinary', 'ordinary')], max_length=100),
        ),
    ]
