# Generated by Django 4.1 on 2022-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0012_remove_subscription_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='highlight',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('urgent', 'urgent'), ('ordinary', 'ordinary')], max_length=100),
        ),
    ]
