# Generated by Django 4.1 on 2022-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0013_subscription_highlight_alter_subscription_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('urgent', 'urgent'), ('ordinary', 'ordinary')], default=('ordinary', 'ordinary'), max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='subscription',
            field=models.ManyToManyField(related_name='posts', to='adds.subscription'),
        ),
    ]
