# Generated by Django 4.1 on 2022-09-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0014_remove_post_subscription_alter_subscription_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='highlight',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='choice',
            field=models.CharField(choices=[('VIP', 'VIP'), ('urgent', 'urgent'), ('ordinary', 'ordinary'), ('highlight', 'highlight')], default=('ordinary', 'ordinary'), max_length=100),
        ),
    ]
