# Generated by Django 4.1 on 2022-09-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0017_reviewpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewpost',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='adds.reviewpost', verbose_name='Parent'),
        ),
    ]
