# Generated by Django 4.0.7 on 2022-09-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_confpolitics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
            ],
        ),
    ]
