# Generated by Django 4.0.7 on 2022-09-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_admintheme_remove_admincontact_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincontact',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admincontact',
            name='adminhat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminhat', to='info.adminhat'),
        ),
    ]
