# Generated by Django 4.0.7 on 2022-09-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='title',
        ),
    ]
